# Generated by Django 5.0.4 on 2024-07-04 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='meals',
            name='special',
            field=models.BooleanField(default=False),
        ),
    ]
