# Generated by Django 5.0.4 on 2024-07-07 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='subject',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
    ]
